# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               all white cheat sheet
tagline:             ' Dana&rsquo;s Swifty Life'
description:         'Dana Daheen Lee<br>#iOS #Swift #CleanCode #Programming'
url:                 http://daheenallwhite.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dana Daheen Lee
  url:               https://github.com/daheenallwhite
  email:             allwhite.dev@gmail.com

# Custom vars
version:             1.0.0

# google analytics
g-analytics: UA-140592254-1

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    